### ISSUE TITLE
[Unconfirmed] Resolved License Violation - now YouTubePlus!

### ISSUE THREAD

**Issue by arichorn** [arichorn/YouTubePlus#2]
Unfortunately i wasn’t able to delete this repository so I private the repo and changed almost everything to just YouTubePlus. a YouTube tweak that adds a new setting section in settings to give you a more friendly customization you all desired most without needing to deal with uYou & Cercube being included! most code was by qnblackcat, PoomSmart, level3tjg, TheRealFoxster & etc.

**Comment by arichorn** [comment]
@LillieH0001 sorry for the mention but is this acceptable to prevent any further action? It took me a bit to adjust this repository so sorry for not reading the LICENSE the right way.

**Comment by arichorn** [comment]
the things I adjusted was the name around the source code and removed stuff related to Reborn to prevent any action from these. Converting this to a Stand-Alone Tweak hasn’t worked yet which ruins the whole purpose of this repo conversation.

**Comment by LillieH001** [comment]
> @LillieH001 sorry for the mention but is this acceptable to prevent any further action? It took me a bit to adjust this repository so sorry for not reading the LICENSE the right way.

Yeah, there is no issue from me as long as yt reborn stuff isn't present.

**Comment by arichorn** [comment]
Oh okay, still sorry about that though.
